version: "3.7"

services: 
  php:
    build: .docker/app
    volumes: 
      - ./:/app
    working_dir: /app
    env_file: 
      - .env
  nginx:
    image: nginx:alpine
    volumes: 
      - .docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports: 
      - 80:80